### ISSUE TITLE
Ошибка в PHP

### ISSUE THREAD

**Issue by neo-azazello** [PHP720/text-errors#6]
Здравствуйте.

Вы написали что "А если бы мы складывали String и String, то получили бы значение 0." Я для проверки не преобразовал в Integer и приплюснул этот стринг. Так почему у меня не вышло 0?

Вот код:

```
<?php
$str = "50000";    // Значение String

// Проверяем... 

echo $str + $str; 
?>
```

Отображение в браузере:

100000

**Comment by scofield-ua** [comment]
@neo-azazello,  вы правы.

Вы можете плюсовать строки (через оператор **+**), только если значения переменных - числа, а не символы. В противном случае вы получите значение **0**.

**Comment by scofield-ua** [comment]
Обновил текст урока.
